### ISSUE TITLE
https://subdomain.panel.com/<shortUuid> is 502

### ISSUE THREAD

**Issue by PunkFleet** [remnawave/subscription-page#14]
i followed  up this guild untile Step 5. 
https://remna.st/docs/install/remnawave-subscription-page/
all is fine just this scription link,  i can't get anything, i set this `sub_page_domain` point to panel ip address. and user and host all is fine, Am I forgetting something? 

<img width="1316" alt="Image" src="https://github.com/user-attachments/assets/76dec013-cdaf-4780-b50a-42861fb643f9" />

<img width="965" alt="Image" src="https://github.com/user-attachments/assets/abf6351c-639c-48f9-ae69-355e96217ad9" />

![Image](https://github.com/user-attachments/assets/c5779c80-8fd2-437f-ba40-97b321aa050a)

**Comment by PunkFleet** [comment]
> > i followed up this guild untile Step 5. https://remna.st/docs/install/remnawave-subscription-page/ all is fine just this scription link, i can't get anything, i set this `sub_page_domain` point to panel ip address. and user and host all is fine, Am I forgetting something?
> > <img alt="Image" width="1316" src="https://private-user-images.githubusercontent.com/86408260/456135995-76dec013-cdaf-4780-b50a-42861fb643f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTAxODMxOTQsIm5iZiI6MTc1MDE4Mjg5NCwicGF0aCI6Ii84NjQwODI2MC80NTYxMzU5OTUtNzZkZWMwMTMtY2RhZi00NzgwLWI1MGEtNDI4NjFmYjY0M2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjE3VDE3NTQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMzVmZTIyMjc2OGM0NGUzMzNkMzg1M2I4OTk5N2U0NmUzYmNmODZmZGM2NTA2MjI5YTA2NjMzNDNkMWQ4NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BdwKY3whL8RlRyIDRAUxi6IXj1cfAK_EopuVdYeM6f4"> <img alt="Image" width="965" src="https://private-user-images.githubusercontent.com/86408260/456136885-abf6351c-639c-48f9-ae69-355e96217ad9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTAxODMxOTQsIm5iZiI6MTc1MDE4Mjg5NCwicGF0aCI6Ii84NjQwODI2MC80NTYxMzY4ODUtYWJmNjM1MWMtNjM5Yy00OGY5LWFlNjktMzU1ZTk2MjE3YWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjE3VDE3NTQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MzAyODAzYTk4ZmMzOGRhMmU4NDljM2MzNDg3ZTI3MjRiZjlhMDYxYjVlNGNmNzg0YjM2NWZjZjI0NmM3ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1i6hZ3OgDqE4BsmSRk8ATlJtRBbbLxZPQoGtdpiOPaM">
> > ![Image](https://github.com/user-attachments/assets/c5779c80-8fd2-437f-ba40-97b321aa050a)
> 
> What is `sub_page_domain`?
> 
> if you mean `SUB_PUBLIC_DOMAIN` it must be set as domain of your subscription-page.
> 
> If you subscription page have domain name – subscription.domain.com, then SUB_PUBLIC_DOMAIN=subscription.domain.com. And after that – restart Remnawave by running docker compose down && docker compose up -d

yup, it's `SUB_PUBLIC_DOMAIN`. i think all is fine . just can't open user subscription link on browser, 
this subscription page docker file:
```
services:
    remnawave-subscription-page:
        image: remnawave/subscription-page:latest
        container_name: remnawave-subscription-page
        hostname: remnawave-subscription-page
        restart: always
        environment:
            - REMNAWAVE_PANEL_URL=https://subscription.mydomain.com
            - APP_PORT=3010
            - META_TITLE="Subscription Page Title"
            - META_DESCRIPTION="Subscription Page Description"
            - CUSTOM_SUB_PREFIX=invoice
        ports:
            - '127.0.0.1:3010:3010'
        networks:
            - remnawave-network

networks:
    remnawave-network:
        driver: bridge
        external: true

```
.env
```
### APP ###
APP_PORT=3000
METRICS_PORT=3001

### API ###
# Possible values: max (start instances on all cores), number (start instances on number of cores), -1 (start instances on all cores - 1)
# !!! Do not set this value more than physical cores count in your machine !!!
# Review documentation: https://remna.st/docs/install/environment-variables#scaling-api
API_INSTANCES=1

### DATABASE ###
# FORMAT: postgresql://{user}:{password}@{host}:{port}/{database}
DATABASE_URL="postgresql://postgres:b0d2d421e121fdca319b21f7017d0a01fd9f46333d4d20ec@remnawave-db:5432/postgres"

### REDIS ###
REDIS_HOST=remnawave-redis
REDIS_PORT=6379

### JWT ###
### CHANGE DEFAULT VALUES ###
JWT_AUTH_SECRET=5803a1d34b1f955435adf5f64624f9e3a0109e53a6b8cb3b4ed1650f9354011f8d8df85e19cd4b3fd81569c56fef3714c1e1235fb09abba728fd71add862fe63
JWT_API_TOKENS_SECRET=4e800b42d1c91379e73a7bd092dee50afd8a051e5d5bd9e8c26e635b548366da4e79dc1fb41c0423f1da4aa5da46f46ceeeeba8c78001314ee6f3a0ac6e0d662

### TELEGRAM NOTIFICATIONS ###
IS_TELEGRAM_NOTIFICATIONS_ENABLED=false
TELEGRAM_BOT_TOKEN=
TELEGRAM_NOTIFY_USERS_CHAT_ID=
TELEGRAM_NOTIFY_NODES_CHAT_ID=

### Telegram Oauth (Login with Telegram) 
### true/false 
TELEGRAM_OAUTH_ENABLED=false
### Array of Admin Chat Ids. These ids will be allowed to login.
TELEGRAM_OAUTH_ADMIN_IDS=[123, 321]

# Optional
# Only set if you want to use topics
TELEGRAM_NOTIFY_USERS_THREAD_ID=
TELEGRAM_NOTIFY_NODES_THREAD_ID=

### FRONT_END ###
# Used by CORS, you can leave it as * or place your domain there
FRONT_END_DOMAIN=panel.mydomain.com

### SUBSCRIPTION PUBLIC DOMAIN ###
### DOMAIN, WITHOUT HTTP/HTTPS, DO NOT ADD / AT THE END ###
### Used in "profile-web-page-url" response header and in UI/API ###
### Review documentation: https://remna.st/docs/install/environment-variables#domains
SUB_PUBLIC_DOMAIN=subscription.mydomain.com/invoice

```
